### ISSUE TITLE
Illu rotation doesn't respond to state changes

### ISSUE THREAD

**Issue by boardfish** [drcmda/react-zdog#10]
Illu rotation doesn't respond to state changes now. You can see it in action by [changing the rotation in the text boxes](https://codesandbox.io/s/divine-sun-l3chy).

_Originally posted by @boardfish in https://github.com/drcmda/react-zdog/issues/9#issuecomment-502382644_

**Comment by drcmda** [comment]
fixed. sorry, had to do with the previous bugfix for the rotation issue.

**Comment by boardfish** [comment]
Wow, that was quick! Thanks again!
