### ISSUE TITLE
dragRotate not working

### ISSUE THREAD

**Issue by jacasch** [drcmda/react-zdog#14]
It looks like `dragRotate` is not working. 

# 

#### this code:

```html
<Illustration zoom={2} dragRotate={true}>
    <Rect width={120} height={80} stroke={10} color="#E62"/>
</Illustration>
```
# 

#### gives this error:

```console
illustration.js:233 Uncaught TypeError: Cannot read property 'x' of undefined
  at Item.Illustration.dragStart (illustration.js:233)
  at Item.Dragger.onmousedown.Dragger.onpointerdown (dragger.js:76)
  at Item.Dragger.handleEvent (dragger.js:71)
```

**Comment by vzalberto** [comment]
Same here. Funny thing is, it does work on https://codesandbox.io/s/frosty-worker-13f0v

Running local gives me this error message 
![image](https://user-images.githubusercontent.com/4513178/66411182-ec58af00-e9b8-11e9-98fa-b3a78295f208.png)

**Comment by drcmda** [comment]
oh it looks like it forwards that one through. could i interest you in a PR? if you depend on this lib i would also share authorship and give push/npm rights. im terribly busy with the other stuff unfortunately.

**Comment by shahruz** [comment]
Hey, just submitted a pull request with a fix!
