### ISSUE TITLE
Doesn't work with cra

### ISSUE THREAD

**Issue by mogmog** [drcmda/react-zdog#25]
`create-react-app zdogreacttest`

`yarn add zdog react-zdog`

replace the contents of app.js with the following minimal app

```
import React from 'react';
import { Illustration, Shape } from 'react-zdog'

function App() {
  return (
      <Illustration zoom={8}>
        <Shape stroke={20} color="lightblue" rotate={{ x: 5 }} />
      </Illustration>
  );
}

export default App;
```
yarn start

Expected behavior - a shape 

Actual behavior - nothing rendered.

No errors in console but when I was fiddling I did once get it to work and saw some errors with event listeners. Cant reproduce anything working now though, so its hard to say.

**Comment by zbaker94** [comment]
Can confirm that this is not working on CRA for me either. Would love some update on this @drcmda
