### ISSUE TITLE
Controlled user input `onDrag`

### ISSUE THREAD

**Issue by brillout** [drcmda/react-zdog#28]
The examples at https://zzz.dog/ are draggable; the user can drag to rotate objects.

Thoughts about a `onDrag()` controlled user input event?

**Comment by bhushan6** [comment]
Hi @brillout , You have onDragMove, onDragStart, onDragEnd events available just the way there are in zdog, is that what you looking for? Just in case thats not working for you, please check if you have set the `dragRotate` prop to `true`, it only works with that. Ik reply is bit late lol.
