### ISSUE TITLE
Support react@18

### ISSUE THREAD

**Issue by JuanSeBestia** [drcmda/react-zdog#34]
Hi. I see that this lib is used by react-spring

I use some animation on my projects, and it still works in react@18. but it still show me the warning when it is installed.

```bash
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: react-reconciler@0.20.4
npm WARN Found: react@18.2.0
npm WARN node_modules/react
npm WARN   react@"^18.2.0" from the root project
npm WARN   106 more (@emotion/react, @emotion/styled, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.0.0" from react-reconciler@0.20.4
npm WARN node_modules/react-zdog/node_modules/react-reconciler
npm WARN   react-reconciler@"^0.20.4" from react-zdog@1.2.1
npm WARN   node_modules/react-zdog
npm WARN 
npm WARN Conflicting peer dependency: react@16.14.0
npm WARN node_modules/react
npm WARN   peer react@"^16.0.0" from react-reconciler@0.20.4
npm WARN   node_modules/react-zdog/node_modules/react-reconciler
npm WARN     react-reconciler@"^0.20.4" from react-zdog@1.2.1
npm WARN     node_modules/react-zdog
```

and also update `react-reconciler` to get rid of this warning

**Comment by bhushan6** [comment]
Hi @JuanSeBestia , seems like there is some package version conflicts due to react-reconciler. Tbh react-reconciler shouldn't be even there, which is weird. Actually I was already in process of migrating to vite and removing unused packages. Let me see if I can push that today, that most probably should fix this.

**Comment by bhushan6** [comment]
Hey @JuanSeBestia ,
I have migrated it to vite and removed unused deps and published a patch. I have tested myself and I don't get that warning anymore, can you please install latest version 1.2.2 and let me know. Thanks.
