### ISSUE TITLE
Allow access to the parent Illustration

### ISSUE THREAD

**Issue by boardfish** [drcmda/react-zdog#8]
This has likely got a similar source to #7. `useRender` can only be used inside of `Illustration`s, but I'd like to be able to change the `rotate` attribute of an `Illustration` on a frame-by-frame basis as you would with:

```
function animate() {
  illo.rotate.y += 0.08
  requestAnimationFrame(animate)
}
```

_Originally posted by @boardfish in https://github.com/drcmda/react-zdog/issues/7#issuecomment-499520438_

**Comment by drcmda** [comment]
this is normal, its context based, and ultimatively there could be multiple illustrations, it has to be part of its tree to know the illustration it targets - no way around that. i could let you access the parent illu maybe, then you could still drive it in a loop (which is part of the component tree).

**Comment by boardfish** [comment]
I like that idea – while children in React should generally be oblivious to their parents, `Shape`s rely on `Illustration`s to exist, so in this case I think it makes sense to do it that way.

**Comment by drcmda** [comment]
it's in. useZdog, documented on the front page
